### ISSUE TITLE
Crahs server posible progresion ?

### ISSUE THREAD

**Issue by kamila231993** [noisiver/mod-progression#10] opened 2024-03-17 00:43 UTC
have 1 crahs server
I have an occasional crash on the server, could something be in progress?

thank you

[Errors.log](https://github.com/noisiver/mod-progression/files/14625695/Errors.log)
[Server.log](https://github.com/noisiver/mod-progression/files/14625696/Server.log)

**Comment by noisiver** [comment] 2024-03-18 01:31
I highly doubt it's because of this module but without a crash log it's 100% impossible to determine. The logs you included give no indication as to what could be causing it at all.

**Comment by SpiderNet193** [comment] 2024-03-18 18:58
how can i make the crash.log file? to activate it

**Comment by noisiver** [comment] 2024-03-18 20:26
It depends on your setup. For Windows you just have to make sure to compile in RelWithDebInfo and for Linux you should read this: https://www.azerothcore.org/wiki/how-to-restart-and-debug

**Comment by noisiver** [comment] 2024-03-18 20:42
Do you happen to have Errors.log that you can share if you're having crashes too @SpiderNet193?

In the one provided in this one it just ends with this:
```
SQL(p): INSERT INTO character_action (guid, spec, button, action, type) VALUES (45, 1, 0, 47610, 0)
 [ERROR]: [1062] Duplicate entry '45-1-0' for key 'PRIMARY'
 ```

The thing is, I don't know if it would crash the server or not when that error pops up, which is another reason why a crash log is required.
 
 There are of course so many other errors in there that I couldn't even begin to guess what could be the cause.

**Comment by noisiver** [comment] 2024-03-21 22:02
I'm closing this due to a lack of information. You are free to open another one if you can provide the necessary information.

**Closed by noisiver** 2024-03-21 22:02 UTC
